doctrine:
#     dbal:
#         connections:
#             default:
#                 url: '%env(resolve:DATABASE_URL'
#             customer:
#                 url: '%env(resove:CUSTOMER_DATABASE_URL'
#         default_connection: default
    
#     orm:
#         default_entity_manager: default
#         entity_managers:
#             default:
#                 connection: default
#                 mappings:
#                     Main:
#                         is_bundle: false
#                         type: annotation
#                         dir: '%kernel.project_dir%/src/Entity/Main'
#                         prefix: 'App\Entity\Main'
#                         alias: Main
#             customer:
#                 connection: customer
#                 mappings:
#                     Customer:
#                         is_bundle: false
#                         type: annotation
#                         dir: '%kernel.project_dir%/src/Entity/Customer'
#                         prefix: 'App\Entity\Customer'
#                         alias: Customer


    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
